apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
namespace: demo

resources:
  - ../../base

# Override image (e.g., your ECR image + tag)
images:
  - name: public.ecr.aws/nginx/nginx
    newName: <YOUR_ECR_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/<ECR_REPOSITORY>
    newTag: dev

patchesStrategicMerge:
  - patch-deployment.yaml
  - patch-service.yaml

configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
      - LOG_LEVEL=debug
      - APP_MODE=development