# base/kustomization.yaml
secretGenerator:
- name: my-secret     # Name of the Secret
  literals:
  - username=admin    # Key-value pairs; consider external management for real secrets
  - password=s3cr3t
