apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
commonLabels:
  app.kubernetes.io/part-of: kustomize-demo

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml

configMapGenerator:
  - name: app-config
    literals:
      - LOG_LEVEL=info
      - APP_MODE=base

# Generate a Secret from literals (do NOT commit real secrets)
secretGenerator:
  - name: app-secret
    literals:
      - API_TOKEN=dummy-token

# Add a suffix hash to force rollouts on changes
generatorOptions:
  disableNameSuffixHash: false

# Images can be overridden by overlays via `images:` transformer
images:
  - name: public.ecr.aws/nginx/nginx
    newTag: latest