apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-demo
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: app
          env:
            - name: FEATURE_FLAG
              value: "staging"